name: Bug report
description: Сообщить о баге
labels: ["bug"]
body:
  - type: input
    id: environment
    attributes:
      label: Окружение
      placeholder: prod / staging / dev
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      placeholder: |
        1. Перейти на страницу...
        2. Нажать кнопку...
        3. Увидеть ошибку...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
