name: Bug report
description: Сообщить о баге
labels: ["bug"]
body:
  - type: input
    id: environment
    attributes:
      label: Окружение
      placeholder: prod / staging / dev
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      placeholder: |
        1. Перейти на страницу...
        2. Нажать кнопку...
        3. Увидеть ошибку...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      options:
        - Critical (REC2DEP)
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: team
    attributes:
      label: Команда
      options:
        - Backend (Марк)
        - Frontend (Макс)
        - DevOps/Support (Андрей)
    validations:
      required: true
