name: Incident report
description: Срочный инцидент (падение домена, недоступность)
labels: ["incident", "critical"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Влияние на пользователей
  - type: textarea
    id: steps_taken
    attributes:
      label: Что уже предпринято
